### ISSUE TITLE
Wrong FS error

### ISSUE THREAD

**Issue by kusum007** [qubole/streamx#1]
I got this Wrong Filesystem error while running the maven tests. I have built the latest snapshot versions of kafka packages.

2016-05-25 16:30:43,710 WARN  [org.apache.hadoop.hdfs.server.blockmanagement.DecommissionManager$Monitor@4163f1cd] blockmanagement.DecommissionManager (DecommissionManager.java:run(78)) - Monitor interrupted: java.lang.InterruptedException: sleep interrupted
2016-05-25 16:30:43,718 INFO  [main] namenode.FSNamesystem (FSNamesystem.java:stopActiveServices(1246)) - Stopping services started for active state
2016-05-25 16:30:43,718 INFO  [main] namenode.FSNamesystem (FSNamesystem.java:stopStandbyServices(1334)) - Stopping services started for standby state
2016-05-25 16:30:43,720 INFO  [main] mortbay.log (Slf4jLog.java:info(67)) - Stopped HttpServer2$SelectChannelConnectorWithSafeStartup@localhost:0
2016-05-25 16:30:43,721 INFO  [main] impl.MetricsSystemImpl (MetricsSystemImpl.java:stop(210)) - Stopping DataNode metrics system...
2016-05-25 16:30:43,722 INFO  [main] impl.MetricsSystemImpl (MetricsSystemImpl.java:stop(216)) - DataNode metrics system stopped.
2016-05-25 16:30:43,722 INFO  [main] impl.MetricsSystemImpl (MetricsSystemImpl.java:shutdown(605)) - DataNode metrics system shutdown complete.
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 3.307 sec <<< FAILURE! - in io.confluent.connect.hdfs.wal.WALTest
testWALMultiClient(io.confluent.connect.hdfs.wal.WALTest)  Time elapsed: 3.302 sec  <<< ERROR!
java.lang.IllegalArgumentException: Wrong FS: file:/tmp/topics/topic/12/5a3b1baf-f9a5-443b-b043-50ea80c7e15d_tmp.avro, expected: hdfs://localhost:9001
    at org.apache.hadoop.fs.FileSystem.checkPath(FileSystem.java:645)
    at org.apache.hadoop.hdfs.DistributedFileSystem.getPathName(DistributedFileSystem.java:193)
    at org.apache.hadoop.hdfs.DistributedFileSystem.access$000(DistributedFileSystem.java:105)
    at org.apache.hadoop.hdfs.DistributedFileSystem$18.doCall(DistributedFileSystem.java:1118)
    at org.apache.hadoop.hdfs.DistributedFileSystem$18.doCall(DistributedFileSystem.java:1114)
    at org.apache.hadoop.fs.FileSystemLinkResolver.resolve(FileSystemLinkResolver.java:81)
    at org.apache.hadoop.hdfs.DistributedFileSystem.getFileStatus(DistributedFileSystem.java:1114)
    at org.apache.hadoop.fs.FileSystem.exists(FileSystem.java:1400)
    at org.apache.hadoop.fs.FileSystem.createNewFile(FileSystem.java:1148)
    at io.confluent.connect.hdfs.wal.WALTest.testWALMultiClient(WALTest.java:54)

Results :

Failed tests:
  HiveIntegrationAvroTest.testHiveIntegrationFieldPartitionerAvro:205 expected:<[hdfs://127.0.0.1:9001/topics/topic/int=16, hdfs://127.0.0.1:9001/topics/topic/int=17, hdfs://127.0.0.1:9001/topics/topic/int=18]> but was:<[]>
  TopicPartitionWriterTest.testWriteRecordFieldPartitioner:148->verify:263 expected:<3> but was:<1>
  TopicPartitionWriterTest.testWriteRecordTimeBasedPartition:189->verify:263 expected:<3> but was:<1>
  HiveIntegrationParquetTest.testHiveIntegrationParquet:149 expected:<[hdfs://127.0.0.1:9001/topics/topic/partition=12]> but was:<[]>
  HiveIntegrationParquetTest.testHiveIntegrationTimeBasedPartitionerParquet:300 expected:<9> but was:<3>
  ParquetHiveUtilTest.testAlterSchema:132 expected:<6> but was:<1>
  ParquetHiveUtilTest.testCreateTable:92 expected:<6> but was:<3>
Tests in error:
  HdfsSinkTaskTest.testSinkTaskStartWithRecovery:98 » IllegalArgument Wrong FS: ...
  AvroHiveUtilTest.testAlterSchema:92->prepareData:146 » IllegalArgument Wrong F...
  AvroHiveUtilTest.testCreateTable:53->prepareData:146 » IllegalArgument Wrong F...
  DataWriterAvroTest.testGetPreviousOffsets:212 » IllegalArgument Wrong FS: file...
  DataWriterAvroTest.testProjectBackWard:401 » FileNotFound File does not exist:...
  DataWriterAvroTest.testProjectNone:459 » FileNotFound File does not exist: hdf...
  DataWriterAvroTest.testRebalance:298 » IllegalArgument Wrong FS: file:/tmp/top...
  DataWriterAvroTest.testRecovery:117 » IllegalArgument Wrong FS: file:/tmp/topi...
  DataWriterAvroTest.testWriteRecord:73 » IllegalArgument Wrong FS: file:/tmp/to...
  DataWriterAvroTest.testWriteRecordMultiplePartitions:176 » IllegalArgument Wro...
  DataWriterAvroTest.testWriteRecordNonZeroInitailOffset:248 » IllegalArgument W...
  HiveIntegrationAvroTest.testHiveIntegrationAvro:126 » IllegalArgument Wrong FS...
  HiveIntegrationAvroTest.testSyncWithHiveAvro:70 » IllegalArgument Wrong FS: fi...
  DataWriterParquetTest.testWriteRecord:81 » FileNotFound File hdfs://127.0.0.1:...
  WALTest.testWALMultiClient:54 » IllegalArgument Wrong FS: file:/tmp/topics/top...

Tests run: 45, Failures: 7, Errors: 15, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 03:39 min
[INFO] Finished at: 2016-05-25T16:30:43-07:00
[INFO] Final Memory: 43M/437M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.18.1:test (default-test) on project kafka-connect-hdfs: There are test failures.
[ERROR]
[ERROR] Please refer to /Users/kushumsharma/backup/github/streamx/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by PraveenSeluka** [comment]
I will add some documentation in the next couple of days - and get to state where you could run it.

**Comment by PraveenSeluka** [comment]
Yes, this tests fail right now. In s3 flow, the temp file gets copied to the local file system (HDFS sink uses hdfs to store temp files). The tests are using HDFS fs implementation and it expects a hdfs path (not a local path) - hence its failing. Currently, I would suggest to skipTests, while we get to fixing the tests.

**Comment by kusum007** [comment]
Okay, Thanks.

**Comment by nahguam** [comment]
Hi, Has there been any progress here fixing the existing tests (and adding tests for the S3 related code)?

**Comment by PraveenSeluka** [comment]
Am going to close this, create another JIRA where we will look into adding tests.
