### ISSUE TITLE
Bug in S3SinkConenctorConfig

### ISSUE THREAD

**Issue by a2mehta** [qubole/streamx#10]
Hello, 

I pulled the latest commit and tried to run it. It resulted in the following error:

[2016-07-07 22:44:42,095] ERROR Uncaught exception in herder work thread, exiting:  (org.apache.kafka.connect.runtime.distributed.DistributedHerder:166)
**java.lang.NoSuchFieldError: config**
    at com.qubole.streamx.s3.S3SinkConnectorConfig.<clinit>(S3SinkConnectorConfig.java:64)
    at com.qubole.streamx.s3.S3SinkConnector.start(S3SinkConnector.java:51)
    at org.apache.kafka.connect.runtime.Worker.addConnector(Worker.java:186)
    at org.apache.kafka.connect.runtime.distributed.DistributedHerder.startConnector(DistributedHerder.java:668)
    at org.apache.kafka.connect.runtime.distributed.DistributedHerder.startWork(DistributedHerder.java:640)
    at org.apache.kafka.connect.runtime.distributed.DistributedHerder.handleRebalanceCompleted(DistributedHerder.java:598)
    at org.apache.kafka.connect.runtime.distributed.DistributedHerder.tick(DistributedHerder.java:184)
    at org.apache.kafka.connect.runtime.distributed.DistributedHerder.run(DistributedHerder.java:159)

Perhaps the following line needs to be added to line 62 of S3SinkConnectorConfig.java? 

protected static ConfigDef config = new ConfigDef();

Thanks

**Comment by PraveenSeluka** [comment]
Hi @a2mehta 

Thats odd. I just did a clean compile and it compiled. S3SinkConnectorConfig is a sub-class of HdfsSinkConnectorConfig and the config variable is defined in HdfsSinkConnectorConfig. I dont see why this should fail for you, can you make sure there are no local changes done.

Thanks

**Comment by a2mehta** [comment]
As a sanity check, can you tell me what directory your confluent-common jar files are and what your CLASSPATH looks like when you run connect-distributed?

Thanks

**Comment by PraveenSeluka** [comment]
export CLASSPATH=$CLASSPATH:`pwd`/target/streamx-0.1.0-SNAPSHOT-development/share/java/streamx/

This is available in README of this project too. Can you do a clean compile once (just to make sure you are not picking any old artifacts)

**Comment by a2mehta** [comment]
I did a fresh clone/build and the result was the same. This is what my CLASSPATH looks like for reference:

:./bin/../share/java/confluent-common/_:./bin/../share/java/kafka-serde-tools/_:./bin/../share/java/kafka-connect-hdfs/_:./bin/../share/java/kafka-connect-jdbc/_:./bin/../share/java/kafka-connect-mongo/_:/projects/streamx/target/streamx-0.1.0-SNAPSHOT-development/share/java/streamx/_

I am using Confluent 2.0.0 if that helps

**Comment by PraveenSeluka** [comment]
I think, I know the problem. You need to use Confluent 3.0.0. Looks like its picking up old HdfsSinkConnectorConfig from Confluent classpath(you have added kafka-connect-hdfs). For streamx, the development dir bundles everything thats required.

**Comment by a2mehta** [comment]
Hi Praveen,

It looks like that was the issue, not using Confluent 3.0.0 and it picking up the HdfsSinkConnectorConfig in the classpath. Thank you for your assistance, I will close this.
