### ISSUE TITLE
NullPointerException after recreating Kafka connector

### ISSUE THREAD

**Issue by dhamilton** [qubole/streamx#35]
I have been using the S3 connector with solid results. Unfortunately I tried recreating a Kafka connector and am seeing the following exception being thrown across all the tasks. Do you know what might cause this and any potential workarounds? Thanks.

[2017-01-28 04:13:45,313] ERROR Task pixel_events_s3-3 threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask:142)
java.lang.NullPointerException
	at io.confluent.connect.hdfs.DataWriter.close(DataWriter.java:299)
	at io.confluent.connect.hdfs.HdfsSinkTask.close(HdfsSinkTask.java:110)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.commitOffsets(WorkerSinkTask.java:301)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.closePartitions(WorkerSinkTask.java:432)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:146)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:140)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:175)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
[2017-01-28 04:13:45,313] ERROR Task is being killed and will not recover until manually restarted (org.apache.kafka.connect.runtime.WorkerTask:143)

**Comment by dhamilton** [comment]
I was just able to get it restarted, not sure what the issue was but I'll close this out.
