### ISSUE TITLE
Writing Avro data

### ISSUE THREAD

**Issue by dhamilton** [qubole/streamx#39]
We needed to switch our key and value converter from io.confluent.connect.avro.AvroConverter to com.qubole.streamx.ByteArrayConverter to support writing CSV/JSON data to S3. Is there a supported way to write Avro files using this configuration? I tried scheduling the job with "format.class=io.confluent.connect.hdfs.avro.AvroFormat" however this does not work for me.

**Comment by PraveenSeluka** [comment]
@dhamilton Is the data in Avro format in Kafka ? Or you wanted the JSON to be converted to AVRO ?

If its in Avro format in Kafka, set the converter to use AvroConverter and you will need to provide schema registry details too (not sure if thats optional)

**Comment by dhamilton** [comment]
Yes the data is in Avro format in Kafka. We managed to get this to work by using "value.converter=io.confluent.connect.avro.AvroConverter" in our properties file but we want to switch to ByteArrayConverter. I tried specifying "value.converter": "io.confluent.connect.avro.AvroConverter" when adding the job, is that correct? This is a piece of the exception I see when I try this:

Caused by: org.apache.avro.AvroRuntimeException: Unknown datum type: io.confluent.kafka.serializers.NonRecordContainer@4be71a53
	at org.apache.avro.generic.GenericData.getSchemaName(GenericData.java:632)
	at org.apache.avro.generic.GenericData.resolveUnion(GenericData.java:597)
	at org.apache.avro.generic.GenericDatumWriter.resolveUnion(GenericDatumWriter.java:151)
	at org.apache.avro.generic.GenericDatumWriter.write(GenericDatumWriter.java:71)
	at org.apache.avro.generic.GenericDatumWriter.write(GenericDatumWriter.java:58)
	at org.apache.avro.file.DataFileWriter.append(DataFileWriter.java:257)
	... 17 more

**Comment by dhamilton** [comment]
I managed to track down the issue. I am using Kafka 0.10.0.1 which does not support per-connector converters. Seems that support was added in 0.10.1.0: https://issues.apache.org/jira/browse/KAFKA-3845

**Comment by rahulbhatia2702** [comment]
@PraveenSeluka @dhamilton  do you know if the schema registry is optional if data in kafka is in AVro ??
