### ISSUE TITLE
org.apache.hadoop.fs.s3a.S3AFileSystem.append not supported

### ISSUE THREAD

**Issue by a2mehta** [qubole/streamx#8]
I am trying out this connector and am running into the following issue. I start the connector and then I send data to the topic it is reading from. I then stop the connector, start it again, and then continue to send data to the same topic it was reading from before. It appears that it is trying to append to the same log file as before and is throwing an exception because append is not a supported operation in S3.

I am wondering if I am using this connector wrong and if this is the intended behavior. Perhaps a potential fix could be to check if that log file already exists and if it does then rename it and create a new one with the old name? However, this approach might break the exactly once guarantee feature, but I am not sure.

Thank you for any insight and guidance

s3 bucket name redacted below:

[2016-06-28 00:18:01,367] INFO Getting path status for s3a://s3 bucket/streamx/logs/streamx/0/log (streamx/logs/streamx/0/log) (org.apache.hadoop.fs.s3a.S3AFileSystem:684)
[2016-06-28 00:18:01,842] INFO Getting path status for s3a://s3 bucket/streamx/logs/streamx/0/log (streamx/logs/streamx/0/log) (org.apache.hadoop.fs.s3a.S3AFileSystem:684)
[2016-06-28 00:18:01,930] INFO Getting path status for s3a://s3 bucket/streamx/logs/streamx/0/log (streamx/logs/streamx/0/log) (org.apache.hadoop.fs.s3a.S3AFileSystem:684)
[2016-06-28 00:18:02,015] INFO Opening 's3a://s3 bucket/streamx/logs/streamx/0/log' for reading (org.apache.hadoop.fs.s3a.S3AFileSystem:221)
[2016-06-28 00:18:02,016] INFO Getting path status for s3a://s3 bucket/streamx/logs/streamx/0/log (streamx/logs/streamx/0/log) (org.apache.hadoop.fs.s3a.S3AFileSystem:684)
[2016-06-28 00:18:02,101] INFO Actually opening file streamx/logs/streamx/0/log at pos 0 (org.apache.hadoop.fs.s3a.S3AFileSystem:84)
**[2016-06-28 00:18:02,190] ERROR Recovery failed at state RECOVERY_PARTITION_PAUSED** (io.confluent.connect.hdfs.TopicPartitionWriter:214)
**org.apache.kafka.connect.errors.ConnectException: Error creating writer for log file s3a://s3 bucket/streamx/logs/streamx/0/log**
    at io.confluent.connect.hdfs.wal.FSWAL.acquireLease(FSWAL.java:91)
    at io.confluent.connect.hdfs.wal.FSWAL.apply(FSWAL.java:105)
    at io.confluent.connect.hdfs.TopicPartitionWriter.applyWAL(TopicPartitionWriter.java:441)
    at io.confluent.connect.hdfs.TopicPartitionWriter.recover(TopicPartitionWriter.java:197)
    at io.confluent.connect.hdfs.TopicPartitionWriter.write(TopicPartitionWriter.java:227)
    at io.confluent.connect.hdfs.DataWriter.write(DataWriter.java:234)
    at io.confluent.connect.hdfs.HdfsSinkTask.put(HdfsSinkTask.java:90)
    at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:280)
    at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:176)
    at org.apache.kafka.connect.runtime.WorkerSinkTaskThread.iteration(WorkerSinkTaskThread.java:90)
    at org.apache.kafka.connect.runtime.WorkerSinkTaskThread.execute(WorkerSinkTaskThread.java:58)
    at org.apache.kafka.connect.util.ShutdownableThread.run(ShutdownableThread.java:82)
**Caused by: java.io.IOException: Not supported
    at org.apache.hadoop.fs.s3a.S3AFileSystem.append(S3AFileSystem.java:268)**
    at org.apache.hadoop.fs.FileSystem.append(FileSystem.java:1173)
    at io.confluent.connect.hdfs.wal.WALFile$Writer.<init>(WALFile.java:221)
    at io.confluent.connect.hdfs.wal.WALFile.createWriter(WALFile.java:67)
    at io.confluent.connect.hdfs.wal.FSWAL.acquireLease(FSWAL.java:73)

**Comment by PraveenSeluka** [comment]
Hi @a2mehta 

it seems you are using FSWAL  which stores the WAL file in s3. And since S3 does not support append, it fails. We cannot use s3 to store WAL for this reason. So, we have implemented DBWAL where it stores the WAL file as database table instead. Here is an example job on how to use DBWAL. Not the properties wal.class and other db.\* properties.

{"name":"twitter connector",
"config":{
"name":"twitter connector",
"connector.class":"com.qubole.streamx.s3.S3SinkConnector",
"tasks.max":"1",
"flush.size":"100000",
"s3.url":"<S3 location>",
"wal.class":"com.qubole.streamx.s3.wal.DBWAL",
"db.connection.url":"jdbc:mysql://localhost:3306/kafka",
"db.user":"<username_required>",
"db.password":"<password_required>",
"hadoop.conf.dir":"<directory where hadoop conf files are stored. Example /usr/lib/hadoop2/etc/hadoop/>",
"topics":"twitter1p"}}
